language: cpp
dist: xenial
compiler:
- clang
- gcc
matrix:
  fast_finish: true
  allow_failures:
    - compiler: clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libboost-chrono-dev libboost-date-time-dev libboost-test-dev libboost-system-dev libboost-filesystem-dev libboost-timer-dev libboost-program-options-dev libboost-thread-dev python-yaml lcov
- gem install coveralls-lcov
script:
- cd cpp
- mkdir -p build
- cd build
- cmake -DENABLE_ASAN:BOOL=ON -DENABLE_OPENCL=OFF ..
- make -j2
- ctest -j4 --output-on-failure
