language: cpp
dist: focal
compiler:
- clang
- gcc
matrix:
  fast_finish: true
  allow_failures:
    - compiler: clang
script:
- cd cpp
- mkdir build
- cd build
- cmake ..
- cmake --build build
- cd build
- ctest --output-on-failure
