trigger:
  - master
jobs:
  - job: run
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS="-Werror" ..
          displayName: 'Build'
      - script: |
          cmake --build build
          cd build ctest
          displayNmae: 'Test'
