name: build
'on':
  push:
    branches:
      - master
jobs:
  ci_test_clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install_ninja
        run: |
          sudo apt update
          sudo apt install ninja-build
        shell: bash
      - name: install_clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 11
          sudo apt-get install clang-tools-11
        shell: bash
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build --target test_clang
  ci_test_gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build --target test_gcc
  ci_test_compilers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - g++-4.8
          - g++-4.9
          - g++-5
          - g++-7
          - g++-8
          - g++-9
          - g++-10
          - clang++-3.5
          - clang++-3.6
          - clang++-3.7
          - clang++-3.8
          - clang++-3.9
          - clang++-4.0
          - clang++-5.0
          - clang++-6.0
          - clang++-7
          - clang++-8
          - clang++-9
          - clang++-10
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: 'cmake --build build --target ci_test_compiler_${{ matrix.compiler }}'
  ci_test_standards:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        standard:
          - 11
          - 14
          - 17
          - 20
        compiler:
          - gcc
          - clang
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: >-
          cmake --build build --target ci_test_${{ matrix.compiler }}_cxx${{
          matrix.standard }}
