parameters:
  # defaults, if not specified
  configuration: 'Release'
  cxxver: '17'

steps:
  - script: | 
    mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    displayName: 'Run CMake to configure build'
    
    - script: | 
    cmake --build build
    displayName: 'Build'
    
    - script: | 
    cd build && ctest
    displayName: 'Run'