name: C/C++ CI
on: 
 push
 paths:
    - '!.github/wordflows/build-gcc.yml'
    - '!.github/wordflows/check-cmake.yml'
    - '!.github/wordflows/install-gcc.yml'
jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest