name: BuildGcc
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  paths:
      - '**.cpp'
jobs:
  gcc-9:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest