name: buildGcc
on:
  push:
    branches:
      - master
        - '**.cpp'
jobs:
  gcc-9:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
