name: clang
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature    
jobs:
  clang-11:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        working-directory: cpp/
        run: mkdir build && cd build
      - name: clang
        working-directory: cpp/
        run: CXX=clang++ CC=clang cmake ..
      - name: build
        working-directory: cpp/
        run: cmake --build build
      - name: test
        working-directory: cpp/
        run: cd build && ctest --verbose
