name: gcc
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feature
      - master
jobs:
  gcc-9:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        working-directory: cpp/
        run: mkdir build && cd build && cmake ..
      - name: build
        working-directory: cpp/
        run: cmake --build build
      - name: test
        working-directory: cpp/
        run: cd build && ctest --verbose
