'on':
  push:
    branches:
      - master
name: go
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
  runs-on: '${{ matrix.platform }}'
  steps:
    - name: configure
      uses: actions/setup-go@v2
      with:
        go-version: '${{ matrix.go-version }}'
    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint
    - name: Run build
      run: go build .
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    - name: Run testing
      run: cd test && go test -v
