name: java
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        java:
          - '8'
          - '11'
          - '15'
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    name: 'Java ${{ matrix.os }} ${{ matrix.Java }}'
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '${{ matrix.java }}'
      - run: cd java && java -cp java Simple
