name: Validate 'setup-go'
on:
  push:
    branches:
      - master

jobs:
  local-cache:
    name: Setup local-cache version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go: [1.13.x, 1.14.x, 1.15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-go ${{ matrix.go }}
        uses: ./
        with:
          go-version: ${{ matrix.go }}

  setup-versions-from-manifest:
    name: Setup ${{ matrix.go }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go: [1.12.16, 1.13.11, 1.14.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: setup-go ${{ matrix.go }}
        uses: ./
        with:
          go-version: ${{ matrix.go }}


  setup-versions-from-dist:
    name: Setup ${{ matrix.go }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go: [1.7, 1.8.6]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup-go ${{ matrix.go }}
      uses: ./
      with:
        go-version: ${{ matrix.go }}

